### ISSUE TITLE
not show statistics or graphical info

### ISSUE THREAD

**Issue by johnfelipe** [datasketch/dane-economia-circular#1]
![SNAG-0059](https://user-images.githubusercontent.com/428820/180300320-35fb70bc-e3ae-4590-820f-d3e8410995b7.png)

**Comment by johnfelipe** [comment]
anyone?

**Comment by johnfelipe** [comment]
```
yarn --version
1.22.19

node -v
v10.19.0

node -v

v18.6.0

npm --version
8.13.2

```

**Comment by facarranza** [comment]
Hi, please let me consult about this problem

**Comment by jpmarindiaz** [comment]
Este repositorio es del frontend del sitio, no del shiny app. El pantallazo hace referencia a que no se ven los gráficos en la shinyapp. Eso es de otro repositorio, le puedes preguntar a @CamilaAchuri

**Comment by johnfelipe** [comment]
How can replicate locally all env?

**Comment by johnfelipe** [comment]
now works
tnks
